nginx:
  build: containers/nginx
  dockerfile: Dockerfile.production
  container_name: 'nginx'
  ports:
    - '80:80'
  volumes_from:
    - datastore
  volumes:
    - ./public:/usr/src/app/public
  links:
    - web

datastore:
  build: containers/datastore
  container_name: 'datastore'

web:
  build: .
  dockerfile: Dockerfile.production
  container_name: 'web'
  ports:
    - '3000:3000'
  environment:
    - RAILS_ENV=production
    - DATABASE_URL
    - SECRET_KEY_BASE
  volumes_from:
    - datastore
  volumes:
    - ./public:/usr/src/app/public
  command: sh /usr/src/app/start.sh