db:
  image: everse/analytics-mysql
  container_name: 'db'
  environment:
    MYSQL_ROOT_PASSWORD: 'test'

nginx:
  build: containers/nginx
  dockerfile: Dockerfile.development
  container_name: 'nginx'
  ports:
    - '80:80'
  volumes_from:
    - datastore
  links:
    - web

datastore:
  build: containers/datastore
  container_name: 'datastore'

web:
  build: .
  dockerfile: Dockerfile.development
  container_name: 'web'
  ports:
    - '3000:3000'
  environment:
    RAILS_ENV: development
    DATABASE_URL: mysql2://root:test@db:3306
    SECRET_KEY_BASE: hogehoge
  volumes_from:
    - datastore
  links:
    - db